version: '3'

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./PyTexasBackend:/opt/PyTexasBackend
      - ./PyTexas2019:/opt/PyTexas2019
    ports:
      - "8000:8000"

  static:
    build:
      context: .
      dockerfile: Dockerfile.static
    command: gulp watch
    volumes:
      - ./PyTexas2019:/opt/PyTexas2019
      - /opt/PyTexas2019/node_modules
